# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.proto',
  package='main',
  syntax='proto3',
  serialized_options=b'Z(github.com/monkrus/grpc-from0;grpc_from0',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cperson.proto\x12\x04main\"y\n\x06sample\x12\x17\n\x0f\x43PU_utilization\x18\x01 \x01(\x05\x12\x11\n\tNetworkIN\x18\x02 \x01(\x05\x12\x12\n\nNetworkOUT\x18\x03 \x01(\x05\x12\x1a\n\x12Memory_utilization\x18\x04 \x01(\x02\x12\x13\n\x0b\x46inalTarget\x18\x05 \x01(\x02\"8\n\x05\x62\x61tch\x12\x10\n\x08\x42\x61tch_ID\x18\x01 \x01(\x05\x12\x1d\n\x07samples\x18\x02 \x03(\x0b\x32\x0c.main.sample\"I\n\x03RFD\x12\r\n\x05RFWID\x18\x01 \x01(\t\x12\x15\n\rlast_batch_id\x18\x02 \x01(\x05\x12\x1c\n\x07\x62\x61tches\x18\x03 \x03(\x0b\x32\x0b.main.batchB*Z(github.com/monkrus/grpc-from0;grpc_from0b\x06proto3'
)




_SAMPLE = _descriptor.Descriptor(
  name='sample',
  full_name='main.sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CPU_utilization', full_name='main.sample.CPU_utilization', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NetworkIN', full_name='main.sample.NetworkIN', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NetworkOUT', full_name='main.sample.NetworkOUT', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Memory_utilization', full_name='main.sample.Memory_utilization', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FinalTarget', full_name='main.sample.FinalTarget', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=143,
)


_BATCH = _descriptor.Descriptor(
  name='batch',
  full_name='main.batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Batch_ID', full_name='main.batch.Batch_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples', full_name='main.batch.samples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=201,
)


_RFD = _descriptor.Descriptor(
  name='RFD',
  full_name='main.RFD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RFWID', full_name='main.RFD.RFWID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_batch_id', full_name='main.RFD.last_batch_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batches', full_name='main.RFD.batches', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=276,
)

_BATCH.fields_by_name['samples'].message_type = _SAMPLE
_RFD.fields_by_name['batches'].message_type = _BATCH
DESCRIPTOR.message_types_by_name['sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['batch'] = _BATCH
DESCRIPTOR.message_types_by_name['RFD'] = _RFD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sample = _reflection.GeneratedProtocolMessageType('sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:main.sample)
  })
_sym_db.RegisterMessage(sample)

batch = _reflection.GeneratedProtocolMessageType('batch', (_message.Message,), {
  'DESCRIPTOR' : _BATCH,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:main.batch)
  })
_sym_db.RegisterMessage(batch)

RFD = _reflection.GeneratedProtocolMessageType('RFD', (_message.Message,), {
  'DESCRIPTOR' : _RFD,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:main.RFD)
  })
_sym_db.RegisterMessage(RFD)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
